export const navbarMenuItems = [
  {
    label: "Cidade",
  },
  {
    label: "Bairro",
  },
];

export const navbarMenuCities = [
  { key: "niteroi", label: "Niteroi" },
  { key: "nova iguacu", label: "Nova Iguaçu" },
  { key: "duque de caxias", label: "Duque de Caxias" },
  { key: "sao goncalo", label: "São Gonçalo" },
];

export const listNiteroiNeighborhood = [
  { key: "atalaia", label: "Atalaia" },
  { key: "badu", label: "Badu" },
  { key: "baldeador", label: "Baldeador" },
  { key: "barreto", label: "Barreto" },
  { key: "cachoeiras", label: "Cachoeiras" },
  { key: "cafuba", label: "Cafuba" },
  { key: "calaboca", label: "Calaboca" },
  { key: "cantagalo", label: "Cantagalo" },
  { key: "caramujo", label: "Caramujo" },
  { key: "centro", label: "Centro" },
  { key: "charitas", label: "Charitas" },
  { key: "cubango", label: "Cubango" },
  { key: "engenho-do-mato", label: "Engenho do Mato" },
  { key: "engenhoca", label: "Engenhoca" },
  { key: "fonseca", label: "Fonseca" },
  { key: "icarai", label: "Icaraí" },
  { key: "ilha-da-conceicao", label: "Ilha da Conceição" },
  { key: "inga", label: "Ingá" },
  { key: "itaipu", label: "Itaipú" },
  { key: "ititioca", label: "Ititioca" },
  { key: "jacaree", label: "Jacareé" },
  { key: "jurujuba", label: "Jurujuba" },
  { key: "largo-da-batalha", label: "Largo da Batalha" },
  { key: "maravista", label: "Maravista" },
  { key: "morro-do-estado", label: "Morro do Estado" },
  { key: "pendotiba", label: "Pendotiba" },
  { key: "piratininga", label: "Piratininga" },
  { key: "santa-barbara", label: "Santa Barbara" },
  { key: "santa-rosa", label: "Santa Rosa" },
  { key: "sao-domingos", label: "São Domingos" },
  { key: "sao-francisco", label: "São Francisco" },
  { key: "sao-lourenco", label: "São Lourenço" },
  { key: "varzea-das-mocas", label: "Varzea das Mocas" },
  { key: "vila-ipiranga", label: "Vila Ipiranga" },
];

export const listNovaIguacuNeighborhood = [
  { key: "bairro-da-luz", label: "Bairro da Luz" },
  { key: "california", label: "Califórnia" },
  { key: "caonze", label: "Caonze" },
  { key: "centro", label: "Centro" },
  { key: "chacrinha", label: "Chacrinha" },
  { key: "engenho-pequeno", label: "Engenho Pequeno" },
  { key: "jardim-iguacu", label: "Jardim Iguaçu" },
  { key: "jardim-tropical", label: "Jardim Tropical" },
  { key: "moqueta", label: "Moquetá" },
  { key: "prata", label: "Prata" },
  { key: "rancho-novo", label: "Rancho Novo" },
  { key: "santa-eugenia", label: "Santa Eugênia" },
  { key: "viga", label: "Viga" },
  { key: "vila-nova", label: "Vila Nova" },
  { key: "vila-operaria", label: "Vila Operária" },
  { key: "ambai", label: "Ambaí" },
  { key: "bairro-botafogo", label: "Bairro Botafogo" },
  { key: "carmary", label: "Carmary" },
  { key: "ceramica", label: "Cerâmica" },
  { key: "kennedy", label: "Kennedy" },
  { key: "nova-america", label: "Nova América" },
  { key: "parque-flora", label: "Parque Flora" },
  { key: "ponto-chic", label: "Ponto Chic" },
  { key: "posse", label: "Posse" },
  { key: "tres-coracoes", label: "Três Corações" },
  { key: "comendador-soares", label: "Comendador Soares" },
  { key: "danon", label: "Danon" },
  { key: "jardim-alvorada", label: "Jardim Alvorada" },
  { key: "jardim-nova-era", label: "Jardim Nova Era" },
  { key: "jardim-palmares", label: "Jardim Palmares" },
  { key: "jardim-pernambuco", label: "Jardim Pernambuco" },
  { key: "ouro-verde", label: "Ouro Verde" },
  { key: "rosa-dos-ventos", label: "Rosa dos Ventos" },
  { key: "cabucu", label: "Cabuçu" },
  { key: "campo-alegre", label: "Campo Alegre" },
  { key: "ipiranga", label: "Ipiranga" },
];

export const listDuqueDeCaxiasNeighborhood = [
  { key: "25-de-agosto", label: "25 de Agosto" },
  { key: "capivari", label: "Capivari" },
  { key: "centenario", label: "Centenário" },
  { key: "centro", label: "Centro" },
  { key: "chacrinha", label: "Chacrinha" },
  { key: "cidade-dos-meninos", label: "Cidade dos Meninos" },
  { key: "codora", label: "Codora" },
  { key: "copacabana", label: "Copacabana" },
  { key: "figueira", label: "Figueira" },
  { key: "gramacho", label: "Gramacho" },
  { key: "imbarie", label: "Imbariê" },
  { key: "itatiaia", label: "Itatiaia" },
  { key: "jardim-anhanga", label: "Jardim Anhangá" },
  { key: "jardim-barro-branco", label: "Jardim Barro Branco" },
  { key: "jardim-gramacho", label: "Jardim Gramacho" },
  { key: "jardim-olimpo", label: "Jardim Olimpo" },
  { key: "jardim-primavera", label: "Jardim Primavera" },
  { key: "laguna-e-dourados", label: "Laguna e Dourados" },
  { key: "nova-campinas", label: "Nova Campinas" },
  { key: "olavo-bilac", label: "Olavo Bilac" },
  { key: "pantanal", label: "Pantanal" },
  { key: "parada-angelica", label: "Parada Angélica" },
  { key: "parada-morabi", label: "Parada Morabi" },
  { key: "parque-beira-mar", label: "Parque Beira Mar" },
  { key: "parque-dois-irmaos", label: "Parque Dois Irmãos" },
  { key: "parque-eldorado", label: "Parque Eldorado" },
  { key: "parque-esperanca", label: "Parque Esperança" },
  { key: "parque-estrela", label: "Parque Estrela" },
  { key: "parque-felicidade", label: "Parque Felicidade" },
  { key: "parque-fluminense", label: "Parque Fluminense" },
  { key: "parque-paulista", label: "Parque Paulista" },
  { key: "parque-vitoria", label: "Parque Vitoria" },
  { key: "pilar", label: "Pilar" },
  { key: "praca-japeri", label: "Praça Japeri" },
  { key: "santa-cruz-da-serra", label: "Santa Cruz da Serra" },
  { key: "santa-lucia", label: "Santa Lúcia" },
  { key: "santa-rosa", label: "Santa Rosa" },
  { key: "santo-antonio", label: "Santo Antônio" },
  { key: "sao-bento", label: "São Bento" },
  { key: "sao-cristovao", label: "São Cristovão" },
  { key: "saracuruna", label: "Saracuruna" },
  { key: "sarapui", label: "Sarapui" },
  { key: "sto-antonio-serra", label: "Sto Antônio Serra" },
  { key: "taquara", label: "Taquara" },
  { key: "trevo-das-missoes", label: "Trevo das Missões" },
  { key: "vila-meriti", label: "Vila Meriti" },
  { key: "vila-urussay", label: "Vila Urussay" },
  { key: "vila-flavia", label: "Vila Flavia" },
  { key: "vila-leopoldina", label: "Vila Leopoldina" },
  { key: "vila-maria-helena", label: "Vila Maria Helena" },
  { key: "vila-operaria", label: "Vila Operaria" },
  { key: "vila-rosario", label: "Vila Rosario" },
  { key: "vila-sao-luiz", label: "Vila São Luiz" },
];

export const listSaoGoncaloNeighborhood = [
  { key: "alcantara", label: "Alcântara" },
  { key: "anaia-grande", label: "Anaia Grande" },
  { key: "arsenal", label: "Arsenal" },
  { key: "laranjal", label: "Laranjal" },
  { key: "morro-do-castro", label: "Morro do Castro" },
  { key: "mutua", label: "Mutuá" },
  { key: "barro-vermelho", label: "Barro Vermelho" },
  { key: "boa-vista", label: "Boa Vista" },
  { key: "boacu", label: "Boaçu" },
  { key: "brasilandia", label: "Brasilândia" },
  { key: "camarao", label: "Camarão" },
  { key: "centro", label: "Centro" },
  { key: "coelho", label: "Coelho" },
  { key: "colubande", label: "Colubandê" },
  { key: "covanca", label: "Covanca" },
  { key: "engenho-pequeno", label: "Engenho Pequeno" },
  { key: "fazenda-dos-mineiros", label: "Fazenda dos Mineiros" },
  { key: "galo-branco", label: "Galo Branco" },
  { key: "gradim", label: "Gradim" },
  { key: "porto-da-madama", label: "Porto da Madama" },
  { key: "guaxindiba", label: "Guaxindiba" },
  { key: "itaitindiba", label: "Itaitindiba" },
  { key: "itaoca", label: "Itaoca" },
  { key: "itauna", label: "Itaúna" },
  { key: "jardim-amendoeira", label: "Jardim Amendoeira" },
  { key: "jardim-catarina", label: "Jardim Catarina" },
  { key: "lagoinha", label: "Lagoinha" },
  { key: "largo-da-ideia", label: "Largo da Ideia" },
  { key: "lindo-parque", label: "Lindo Parque" },
  { key: "luis-cacador", label: "Luís Caçador" },
  { key: "maria-paula", label: "Maria Paula" },
  { key: "mutondo", label: "Mutondo" },
  { key: "neves", label: "Neves" },
  { key: "nova-cidade", label: "Nova Cidade" },
  { key: "novo-mexico", label: "Novo México" },
  { key: "pacheco", label: "Pacheco" },
  { key: "parada-40", label: "Parada 40" },
  { key: "paraiso", label: "Paraíso" },
  { key: "patronato", label: "Patronato" },
  { key: "pita", label: "Pita" },
  { key: "porto-do-rosa", label: "Porto do Rosa" },
  { key: "porto-novo", label: "Porto Novo" },
  { key: "porto-da-pedra", label: "Porto da Pedra" },
  { key: "porto-velho", label: "Porto Velho" },
  { key: "raul-veiga", label: "Raul Veiga" },
  { key: "rio-do-ouro", label: "Rio do Ouro" },
  { key: "rocha", label: "Rocha" },
  { key: "sacramento", label: "Sacramento" },
  { key: "salgueiro", label: "Salgueiro" },
  { key: "santa-catarina", label: "Santa Catarina" },
  { key: "santa-isabel", label: "Santa Isabel" },
  { key: "sao-miguel", label: "São Miguel" },
  { key: "tribobo", label: "Tribobó" },
  { key: "trindade", label: "Trindade" },
  { key: "varzea-das-mocas", label: "Várzea das Moças" },
  { key: "venda-da-cruz", label: "Venda da Cruz" },
  { key: "vila-candoza", label: "Vila Candoza" },
  { key: "vila-lage", label: "Vila Lage" },
  { key: "vista-alegre", label: "Vista Alegre" },
  { key: "ze-garoto", label: "Zé Garoto" },
];

export const listGrausdeEnsino = [
  { key: "infantil", label: "Educação Infantil" },
  { key: "fundamental", label: "Ensino Fundamental" },
  { key: "medio", label: "Ensino Médio" },
  { key: "superior", label: "Ensino Superior" },
];

export const animals = [
  { key: "cat", label: "Cat" },
  { key: "dog", label: "Dog" },
  { key: "elephant", label: "Elephant" },
  { key: "lion", label: "Lion" },
  { key: "tiger", label: "Tiger" },
  { key: "giraffe", label: "Giraffe" },
  { key: "dolphin", label: "Dolphin" },
  { key: "penguin", label: "Penguin" },
  { key: "zebra", label: "Zebra" },
  { key: "shark", label: "Shark" },
  { key: "whale", label: "Whale" },
  { key: "otter", label: "Otter" },
  { key: "crocodile", label: "Crocodile" },
];

export const estadosBrasil = [
  { key: "AC", label: "Acre" },
  { key: "AL", label: "Alagoas" },
  { key: "AP", label: "Amapá" },
  { key: "AM", label: "Amazonas" },
  { key: "BA", label: "Bahia" },
  { key: "CE", label: "Ceará" },
  { key: "DF", label: "Distrito Federal" },
  { key: "ES", label: "Espírito Santo" },
  { key: "GO", label: "Goiás" },
  { key: "MA", label: "Maranhão" },
  { key: "MT", label: "Mato Grosso" },
  { key: "MS", label: "Mato Grosso do Sul" },
  { key: "MG", label: "Minas Gerais" },
  { key: "PA", label: "Pará" },
  { key: "PB", label: "Paraíba" },
  { key: "PR", label: "Paraná" },
  { key: "PE", label: "Pernambuco" },
  { key: "PI", label: "Piauí" },
  { key: "RJ", label: "Rio de Janeiro" },
  { key: "RN", label: "Rio Grande do Norte" },
  { key: "RS", label: "Rio Grande do Sul" },
  { key: "RO", label: "Rondônia" },
  { key: "RR", label: "Roraima" },
  { key: "SC", label: "Santa Catarina" },
  { key: "SP", label: "São Paulo" },
  { key: "SE", label: "Sergipe" },
  { key: "TO", label: "Tocantins" },
];

export const filtroporValor = [
  { key: "Mais Barato", label: "Mais Barato" },
  { key: "Mais Caro", label: "Mais Caro" },
];
